---
title: "xxx"
author: "xxx"
date: "2018/12/5"
output: 
  html_document:
    toc: true
    
---

##Model Introduction 

[Ward's method](https://www.stat.cmu.edu/~cshalizi/350/lectures/08/lecture-08.pdf/ 'ward')
 says that the distance between two clusters, A and B, is how
much the sum of squares will increase when we merge them:
$$
\Delta(A,B) = \sum_{i\in A \bigcup B} ||\overrightarrow{x_i} - \overrightarrow{m}_{A \bigcup B}||^2 - \sum_{i \in A}||\overrightarrow{x_i} - \overrightarrow{m}_A||^2 -\sum_{i \in B}||\overrightarrow{x_i}- \overrightarrow{m}_B||^2 
= \frac{n_An_B}{n_A+n_B} ||\overrightarrow{m}_A- \overrightarrow{m}_B||^2
$$ 

where $\overrightarrow{m}_j$is the center of cluster j, and $n_j$ is the number of points in it. $\Delta$ is called the merging cost of combining the clusters A and B.
With hierarchical clustering, the sum of squares starts out at zero (because every point is in its own cluster) and then grows as we merge clusters. Ward’s method keeps this growth as small as possible.
\
\



The [Euclidean distance](https://en.wikipedia.org/wiki/Euclidean_distance/ 'Euclidean distance') is the "ordinary" straight-line distance between two points in Euclidean space.

$$
d(p,q) = d(q,p) = \sqrt{(q_1 -p_1)^2 + (q_2 - p_2)^2 + \cdots + (q_n -p_n)^2} = \sqrt{\sum_{i=1} (q_i-p_i)^2}
$$


##Dataset: [Black Friday](https://www.kaggle.com/mehdidag/black-friday/ 'Black Friday')

In this tutorial, we choose the dataset on Black Friday with 6 variables. Dataset of 550 000 observations about the black Friday in a retail store, it contains different kinds of variables either numerical or categorical. It contains missing values. 

The description of the variables we use can be found below. \
User_ID: User ID \
Product_ID: Product ID \
Gender: F(female), M(male) \
Age: Age in bins \
Occupation: Occupation (0-20) \
Product_Category_1: Product Category \
Purchase: Purchase amount in dollars \

